stages:
  # - installDeps
  # - test
  # - quality
  - deploy

# installDeps-job:
#   image: node:19-alpine
#   stage: installDeps
#   script:
#     - npm install
#   cache:
#     key: 'dependencies'
#     paths:
#       - node_modules/
#       - package-lock.json
#   only:
#   - main
#   - dev

# test-job:
#   image: node:19-alpine
#   stage: test
#   cache:
#     key: 'dependencies'
#     paths:
#       - node_modules/
#       - package-lock.json
#     policy: pull
#   script:
#     - npm run test
#   only:
#     - main
#     - dev

# quality-job:
#   image: node:19-alpine
#   stage: quality
#   cache:
#     key: 'dependencies'
#     paths:
#       - node_modules/
#       - package-lock.json
#     policy: pull
#   script:
#     - npm run lint
#   only:
#     - main
#     - dev
#   allow_failure: true

deploy-job:
  tags:
    - webshop_api
  image: docker:latest
  services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  stage: deploy
  script:
    - npm run deploy
  only:
    - main
    - dev


