stages:
  - installDeps
  - test
  - quality
  - build

installDeps-job:
  stage: installDeps
  image: node:16-alpine
  script:
    - npm install
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json

test-job:
  stage: test
  image: node:16-alpine
  script:
    - npm test
  cache:
    policy: pull
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json

quality-job:
  stage: quality
  image: node:16-alpine
  script:
    - npm lint
  cache:
    key: 'dependencies'
    policy: pull
    paths:
      - node_modules/
      - package-lock.json

build-job:
  stage: build
  image: node:16-alpine
  script:
    - npm run build
  cache:
    key: 'dependencies'
    policy: pull
    paths:
      - node_modules/
      - package-lock.json


