stages:
  - installDeps
  - test
  - quality
  - deploy

default:
  image: node:latest

installDeps-job:
  stage: installDeps
  script:
    - npm install
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json
  only:
  - main
  - dev

test-job:
  stage: test
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json
    policy: pull
  script:
    - npm run test
  only:
    - main
    - dev

quality-job:
  stage: quality
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json
    policy: pull
  script:
    - npm run lint
  only:
    - main
    - dev
  allow_failure: true

deploy-job:
  stage: deploy
  image: docker:19.03.11
  services:
    - docker:19.03.11-dind
  script:
    - ./deploy.sh
  only:
    - main
    - dev


