stages:
  - installDeps
  - test
  - quality

default:
  image: node:16-alpine
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json
    policy: pull
  only:
    - main
    - dev

installDeps-job:
  stage: installDeps
  script:
    - npm install
  cache:
    policy: pull-push

test-job:
  stage: test
  script:
    - npm test

quality-job:
  stage: quality
  script:
    - npm run lint


