stages:
  - installDeps
  - test
  - quality
  - deploy

installDeps-job:
  stage: installDeps
  image: node:16-alpine
  script:
    - npm install
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json

test-job:
  stage: test
  image: node:16-alpine
  script:
    - npm test
  cache:
    key: 'dependencies'
    paths:
      - node_modules/
      - package-lock.json
    policy: pull

quality-job:
  stage: quality
  image: node:16-alpine
  script:
    - npm run lint
  cache:
    key: 'dependencies' 
    paths:
      - node_modules/
      - package-lock.json
    policy: pull

pages:
  stage: deploy
  image: node:16-alpine
  script:
    - npx tsc
    - cp -r dist/ public
  cache:
    key: 'dependencies' 
    paths:
      - node_modules/
      - package-lock.json
    policy: pull
  artifacts:
    paths:
      - public


